pryvehiculos/apps/vehiculos/urls.py
from django.urls import path
from apps.vehiculos.views import listVehiculos, vehiculoCreate, vehiculoDelete, vehiculoUpdate

app_name='vehiculos'
urlpatterns = [
    path('', listVehiculos, name= 'listVehiculos'),
    path('nuevo/', vehiculoCreate, name= 'vehiculoCreate'),
    path('delete/<int:id>', vehiculoDelete, name='vehiculoDelete'),
    path('update/<int:id>', vehiculoUpdate, name='vehiculoUpdate'),
]

pryvehiculos/pryvehiculos/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.vehiculos.views import home

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('vehiculos/', include('apps.vehiculos.urls', namespace="vehiculos")),
]

pryvehiculos/apps/vehiculos/models.py
from django.db import models

# Create your models here.

class Marca(models.Model):
    nombre = models.CharField(max_length=60)

    def __str__(self):
        return self.nombre

class TipoVehiculo(models.Model):
    nombre = models.CharField(max_length=40)

    def __str__(self):
        return self.nombre

class Vehiculo(models.Model):
    modelo = models.CharField(max_length=30)
    color = models.CharField(max_length=20)
    placa = models.CharField(max_length=15)
    motor = models.CharField(max_length=10)
    marca = models.ForeignKey(Marca, null=True, blank=True, on_delete=models.CASCADE)
    tipovehiculo = models.ForeignKey(TipoVehiculo, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.modelo

pryvehiculos/apps/ventas/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.vehiculos.models import Vehiculo

# Create your models here.

class Venta(models.Model):
    fecha = models.DateField()
    valorTotal = models.BigIntegerField()
    tipoPago = models.CharField(max_length=20)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    vehiculo = models.ManyToManyField(Vehiculo, through='VehiculoVenta')

    def _str_(self):
        return self.tipoPago

class VehiculoVenta(models.Model):
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE, blank=False, null=False)
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE, blank=False, null=False)
    cantidad = models.IntegerField()
    precio = models.BigIntegerField()

pryvehiculos/apps/vehiculos/views.py
from django.shortcuts import render, redirect
from apps.vehiculos.formVehiculo import VehiculoForm
from apps.vehiculos.models import Vehiculo

# Create your views here.

def listVehiculos(request):
    vehiculos = Vehiculo.objects.all().order_by('-id')
    context = {'vehiculos': vehiculos}
    return render(request, 'vehiculos/listVehiculos.html', context)

def home(request):
    return render(request, 'base/base.html')

def vehiculoCreate(request):
    if request.method == 'POST':
        form = VehiculoForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('vehiculos:listVehiculos')
    else:
        form=VehiculoForm()
    return render(request, 'vehiculos/vehiculo_form.html', {'form':form})

def vehiculoUpdate(request,id):
    vehiculo = Vehiculo.objects.get(id=id)
    if request.method == 'GET':
        form = VehiculoForm(instance=vehiculo)
    else:
        form = VehiculoForm(request.POST, instance=vehiculo)
        if form.is_valid():
            form.save()
            return redirect('home')
    return render(request, 'vehiculos/vehiculo_form.html', {'form':form})

def vehiculoDelete(request,id):
    vehiculo = Vehiculo.objects.get(id=id)
    vehiculo.delete()
    return redirect('vehiculos:listVehiculos')

pryvehiculos/apps/ventas/views.py
from django.shortcuts import render

# Create your views here.

pryvehiculos/templates/base/base.html
{%load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
          <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav me-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Inicio
                  <span class="visually-hidden">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'vehiculos:listVehiculos' %}">Vehiculos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">About</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Separated link</a>
                </div>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-sm-2" type="text" placeholder="Search">
              <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>


      {% block content %}

      {% endblock %}

      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
</body>
</html>

pryvehiculos/templates/vehiculos/listVehiculos.html
{% extends 'base/base.html' %}

{% block content %}


    <h1 class="pull-right">
        <div class="row">
            <div class="col-4">
                <h3>Listado de Vehiculos</h3>
            </div>

            <div class="col-4">

            </div>

            <div class="col-4">
                <a href="{% url 'vehiculos:vehiculoCreate' %}" class="btn btn-primary pull-right" style="margin-top: -10px; margin-bottom: 5px;">Adicionar</a>
            </div>
        </div>
        
    </h1>

    <table class="table table-success table-striped">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Modelo</th>
            <th scope="col">Color</th>
            <th scope="col">Placa</th>
            <th scope="col">Motor</th>
            <th scope="col">Marca</th>
            <th scope="col">Tipo Vehiculo</th>
          </tr>
        </thead>
        <tbody>
          {% if vehiculos %}
            {% for vehiculo in vehiculos %}
                <tr>
                    <td>{{ vehiculo.id }}</td>
                    <td>{{ vehiculo.modelo }}</td>
                    <td>{{ vehiculo.color }}</td>
                    <td>{{ vehiculo.placa }}</td>
                    <td>{{ vehiculo.motor }}</td>
                    <td>{{ vehiculo.marca }}</td>
                    <td>{{ vehiculo.tipovehiculo }}</td>
                    <td>
                        <a href="{% url 'vehiculos:vehiculoDelete' vehiculo.id %}" class="btn btn-primary">eliminar</a>
                        <a href="{% url 'vehiculos:vehiculoUpdate' vehiculo.id %}" class="btn btn-primary">editar</a>
                    </td>
                </tr>
            {% endfor %}
          {% else %}
              <h3>No existen registro</h3>
          {% endif %}
        </tbody>
      </table>

{% endblock %}

pryvehiculos/templates/vehiculos/vehiculo_form.html
{% extends 'base/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button class="btn btn-primary" type="submit">
            Guardar Datos
        </button>
    </form>
{% endblock %}